# Use root/example as user/password credentials
version: '3.1'

services:

  mongodb:
    image: mongo:5.0.14
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  postgres:
    image: postgres:15.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
